---
- hosts: dev
  become: yes
  remote_user: vagrant
  roles:
    - common
    - nginx
    - ruby
    - mysql
    - app
  vars_files:
    - ../private/rss2slack/secret_vars.yml
  vars:
    ssh_port: 22
