# This is the configuration used to check the rubocop source code.

# inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'conf/*.rb'
    - 'spec/spec_helper.rb'

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80

Metrics/ParameterLists:
  CountKeywordArgs: true
  Max: 10

Metrics/MethodLength:
  CountComments: false
  Max: 25

ColonMethodCall:
  Enabled: false
