app:
  env: 'staging'
slack:
  incoming_webhooks_url: '{{ staging_incoming_webhooks_url }}'
  outgoing_webhooks_token: '{{ staging_outgoing_webhooks_token }}'
  accept_team_domain: '{{ staging_accept_team_domain }}'
  accept_channel_id: '{{ staging_accept_channel_id }}'
logger:
  runner:
    path: "/var/log/rss2slack/runner.log"
  app:
    path: "/var/log/rss2slack/app.log"
mysql:
  host: '{{ staging_db_host }}'
  database: '{{ db_database }}'
  username: '{{ db_user }}'
  password: '{{ db_password }}'
