---
- name: install dependences package
  yum: name={{item}} state=present
  with_items:
    - git
    - gcc
    - openssl-devel
    - readline-devel
    - bzip2
  tags: ruby

- name: clone rbenv
  git: repo=https://github.com/sstephenson/rbenv.git dest=/usr/local/rbenv
  tags: ruby

- name: clone ruby-build
  git: repo=https://github.com/sstephenson/ruby-build.git dest=/usr/local/rbenv/plugins/ruby-build
  tags: ruby

- name: copy rbenv.sh
  copy: src="rbenv.sh" dest=/etc/profile.d/rbenv.sh owner=root group=root mode=0755
  tags: ruby

- name: exec sh
  shell: /etc/profile.d/rbenv.sh
  tags: ruby

- name: install ruby 
  shell: /bin/bash -lc "rbenv install {{ruby_version}}"
  tags: ruby

- name: set ruby
  shell: /bin/bash -lc "rbenv global {{ruby_version}}"
  tags: ruby

- name: rehash rbenv
  shell: /bin/bash -lc "rbenv rehash"
  tags: ruby

- name: install bundler
  shell: /bin/bash -lc "gem install bundler"
  tags: ruby

- name: echo ruby version
  command: which ruby
  tags: ruby
