---
- name: open http port
  firewalld: service=http permanent=true state=enabled immediate=true
  tags: nginx

- name: open https port
  firewalld: service=https permanent=true state=enabled immediate=true
  tags: nginx
