---
- name: open http port
  firewalld: service=http permanent=true state=enabled
  notify: restart firewalld
  tags: nginx

- name: open https port
  firewalld: service=https permanent=true state=enabled
  notify: restart firewalld
  tags: nginx
