---
- name: start firewalld for dev or staging
  service:
    name: firewalld
    state: started
    enabled: yes
  when: (inventory_hostname in groups['dev']) or (inventory_hostname in groups['staging'])
  tags: nginx

- name: open http port
  firewalld: service=http permanent=true state=enabled immediate=true
  tags: nginx

- name: open https port
  firewalld: service=https permanent=true state=enabled immediate=true
  tags: nginx
