---
- name: create ssl certs dir for dev or staging
  file:
    path: /etc/ssl/certs
    state: directory
    owner: root
    group: root
  when: (inventory_hostname in groups['dev']) or (inventory_hostname in groups['staging'])
  tags: nginx

- name: create ssl private dir for dev or staging
  file:
    path: /etc/ssl/private
    state: directory
    owner: root
    group: root
  when: (inventory_hostname in groups['dev']) or (inventory_hostname in groups['staging'])
  tags: nginx

- name: upload dev ssl certs
  copy:
    src: "{{ inventory_dir }}/../private/rss2slack/dev_rss2slack.crt"
    dest: /etc/ssl/certs/rss2slack.crt
  when: inventory_hostname in groups['dev']
  tags: nginx

- name: upload dev ssl key
  copy:
    src: "{{ inventory_dir }}/../private/rss2slack/dev_rss2slack.key"
    dest: /etc/ssl/private/rss2slack.key
  when: inventory_hostname in groups['dev']
  tags: nginx
