---
- name: upload nginx.conf
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags: nginx

- name: upload dev default.conf
  template: src=dev_default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  when: inventory_hostname in groups['dev']
  tags: nginx

- name: upload staging default.conf
  template: src=staging_default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  when: inventory_hostname in groups['staging']
  tags: nginx

- name: upload prod default.conf
  template: src=prod_default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx
  when: inventory_hostname in groups['prod']
  tags: nginx
