---
- name: installed mysql?
  shell: /bin/bash -lc "which mysql"
  register: mysql_installed
  failed_when: mysql_installed.rc not in [0, 1]
  tags: mysql

- name: remove mariaDB libs
  yum: name=mariadb-libs state=absent
  when: mysql_installed.rc == 1
  tags: mysql

- name: delete mariaDB path
  file: path=/var/lib/mysql/ state=absent
  when: mysql_installed.rc == 1
  tags: mysql

- name: install mysql rpm from remote repo
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el7-8.noarch.rpm
    state: present
  when: mysql_installed.rc == 1
  tags: mysql

- name: install mysql
  yum: name=mysql-community-server state=present
  when: mysql_installed.rc == 1
  tags: mysql

- name: install MySQL-python
  yum: name=MySQL-python state=present
  when: mysql_installed.rc == 1
  tags: mysql

- name: start mysql
  service: name=mysqld enabled=yes state=started
  when: mysql_installed.rc == 1
  tags: mysql

- name: get tmp password for root
  shell: cat /var/log/mysqld.log | grep "temporary password" | awk '{print $11}'
  register: tmp_db_password
  when: mysql_installed.rc == 1
  tags: mysql

- name: upload .tmp.my.cnf for root
  template: src=.tmp.my.cnf dest=/tmp/.tmp.my.cnf
  when: mysql_installed.rc == 1
  tags: mysql

- name: set new password for root
  shell: mysql --defaults-file=/tmp/.tmp.my.cnf -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ db_root_password }}'"
  when: mysql_installed.rc == 1
  tags: mysql

- name: upload .my.cnf for root
  template: src=.my.cnf dest=/tmp/.my.cnf
  when: mysql_installed.rc == 1
  tags: mysql

- name: create database
  mysql_db:
    name: '{{ db_database }}'
    config_file: /tmp/.my.cnf
    state: present
  when: mysql_installed.rc == 1
  tags: mysql

- name: create user
  mysql_user:
    name: '{{ db_user }}'
    password: '{{ db_password }}'
    priv: '{{ db_database }}.*:ALL,GRANT'
    config_file: /tmp/.my.cnf
    state: present
  when: mysql_installed.rc == 1
  tags: mysql

- name: upload create_tables.sql
  copy: src=create_tables.sql dest=/tmp/create_tables.sql mode=0755
  when: mysql_installed.rc == 1
  tags: mysql

- name: exec create_tables.sql
  mysql_db:
    name: '{{ db_database }}'
    state: import
    target: /tmp/create_tables.sql
    config_file: /tmp/.my.cnf
  when: mysql_installed.rc == 1
  tags: mysql

- name: upload my.cnf
  copy: src=my.cnf dest=/etc/my.cnf
  when: mysql_installed.rc == 1
  tags: mysql

- name: install mysql-devel
  yum: name=mysql-devel state=present
  when: mysql_installed.rc == 1
  tags: mysql

- name: create mysql log dir
  file:
    path: /var/log/mysql
    state: directory
    mode: 0755
    owner: mysql
    group: mysql
  tags: mysql

- name: upload logrotate conf
  copy:
    src: logrotate
    dest: /etc/logrotate.d/mysql
    mode: 0644
    owner: root
    group: root
  tags: mysql

- name: restart mysql
  service: name=mysqld state=restarted
  when: mysql_installed.rc == 1
  tags: mysql

- name: exec mysql_config_editor
  expect:
    command: mysql_config_editor set --login-path=client --user='{{ db_user }}' --host=localhost --password
    responses:
      "Enter password:": "{{ db_password }}"
  tags: mysql
