---
- name: register user
  user:
    name={{ssh_user}}
    state=present
    password={{ssh_password}}
    groups={{ssh_groups}}
  tags: users

- name: set dev or staging authorized_keys
  authorized_key:
    user: '{{ ssh_user }}'
    key: "{{ lookup('file', '/Users/naoto/.ssh/id_rsa_dev.pub') }}"
  when: (inventory_hostname in groups['dev']) or (inventory_hostname in groups['staging'])
  tags: users

- name: set prod authorized_keys
  authorized_key:
    user: '{{ ssh_user }}'
    key: "{{ lookup('file', '/Users/naoto/.ssh/id_rsa_rss2slack.pub') }}"
  when: inventory_hostname in groups['prod']
  tags: users

- name: set sudoers.d/
  lineinfile: dest=/etc/sudoers.d/{{ssh_user}} line="{{ssh_user}} ALL=(ALL) NOPASSWD:ALL" create=yes owner=root group=root mode=0440
  tags: common

- name: update system
  command: yum -y update

- name: set locale
  command: localectl set-locale {{ base_locale }}

- name: set timezone
  command: timedatectl set-timezone {{ base_timezone }}

- name: install base package
  yum: name={{item}} state=present
  with_items:
    - git
    - ntp
    - sysstat

- name: start ntpd
  service: name=ntpd state=started enabled=yes

- name: start crond
  service: name=crond state=started enabled=yes

- name: show SELinux
  shell: getenforce
  tags: selinux

- name: set permissive mode
  selinux: policy=targeted state=permissive
  tags: selinux

- name: set ssh conf. (change port, ban root login, only ssh auth, deny pass login.)
  template: src="sshd_config" dest="/etc/ssh/sshd_config" owner=root group=root mode=0600
  notify: restart sshd and firewalld
  tags: sshd

- name: allow dev or staging ssh port
  firewalld: port={{ dev_or_staging_ssh_port }}/tcp permanent=true state=enabled
  notify: restart sshd and firewalld
  when: (inventory_hostname in groups['dev']) or (inventory_hostname in groups['staging'])
  tags: firewalld

- name: allow prod ssh port
  firewalld: port={{ prod_ssh_port }}/tcp permanent=true state=enabled
  notify: restart sshd and firewalld
  when: inventory_hostname in groups['prod']
  tags: firewalld

- name: deny default ssh port
  firewalld: service=ssh permanent=true state=disabled
  notify: restart sshd and firewalld
  tags: firewalld
