-- create database
CREATE DATABASE IF NOT EXISTS `rss2slack` CHARACTER SET utf8;
USE `rss2slack`;

-- create tables
-- FEED
CREATE TABLE IF NOT EXISTS `FEED`(
  `FEED_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'FEED_ID',
  `FEED_NAME` VARCHAR(255) NOT NULL COMMENT 'FEED_NAME',
  `URL` VARCHAR(255) NOT NULL UNIQUE COMMENT 'URL',
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (`FEED_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = 'フィード';

-- ARTICLE
CREATE TABLE IF NOT EXISTS `ARTICLE`(
  `ARTICLE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ARTICLE_ID',
  `TITLE` VARCHAR(255) NOT NULL COMMENT 'TITLE',
  `BODY` VARCHAR(3072) NULL COMMENT 'BODY',
  `URL` VARCHAR(255) NOT NULL UNIQUE COMMENT 'URL',
  `PUB_DATE` DATETIME NULL COMMENT 'PUB_DATE',
  `CREATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  `UPDATED_AT` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (`ARTICLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT = '記事';
