-- create database
CREATE DATABASE IF NOT EXISTS `rss2slack` CHARACTER SET utf8;
USE `rss2slack`;

-- create tables
CREATE TABLE IF NOT EXISTS `FEED`(
  `FEED_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'FEED_ID',
  `FEED_NAME` VARCHAR(255) NOT NULL UNIQUE COMMENT 'FEED_NAME',
  `URL` VARCHAR(255) NOT NULL UNIQUE COMMENT 'URL',
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (`FEED_ID`)
) COMMENT = 'フィード';

CREATE TABLE IF NOT EXISTS `ARTICLE`(
  `ARTICLE_ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ARTICLE_ID',
  `TITLE` VARCHAR(255) NULL COMMENT 'TITLE',
  `DESCRIPTION` VARCHAR(255) NULL COMMENT 'DESCRIPTION',
  `BODY` VARCHAR(3072) NULL COMMENT 'BODY',
  `URL` VARCHAR(255) NULL COMMENT 'URL',
  `CREATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'CREATED_AT',
  `UPDATED_AT` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'UPDATED_AT',
  PRIMARY KEY (`ARTICLE_ID`)
) COMMENT = '記事';

