---
- name: install base package
  yum:
    name: '{{item}}'
    state: present
  with_items:
    - git
    - wget
  tags: jenkins

- name: install open JDK 8
  yum:
    name: java-1.8.0-openjdk
    state: present
  tags: jenkins

- name: get jenkins yum repository
  yum_repository:
    name: jenkins
    description: "jenkins YUM repo"
    baseurl: "http://pkg.jenkins-ci.org/redhat-stable/"
  tags: jenkins

- name: install jenkins key
  rpm_key:
    key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
  tags: jenkins

- name: install jenkins 
  yum:
    name: jenkins
    state: present
  notify: restart jenkins
  tags: jenkins
